services:
  routes:
    - name: identity-provider
      prefix: '/identity-api'
      target: 'http://localhost:5500'

    - name: client-list
      prefix: '/client-list-api'
      target: 'http://localhost:4500'

  exclusions:
    - '/favicon.ico'
    - '/'
